"""add menu_configs table

Revision ID: 177afad4a430
Revises: 0e85d2cae605
Create Date: 2026-04-26 18:38:58.400890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177afad4a430'
down_revision: Union[str, Sequence[str], None] = '0e85d2cae605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: fk_users_company_id was added in 0e85d2cae605 and kept for data integrity.
    # Alembic autogenerates a drop because the ORM model doesn't declare the FK.
    # We intentionally skip that drop line below.
    op.create_table('menu_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('student', 'manager', 'admin', name='menu_role'), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'role', name='uq_menu_configs_tenant_role')
    )
    # FK retained from 0e85d2cae605 (not dropped — listed in User model now)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_users_company_id'), 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_table('menu_configs')
    # ### end Alembic commands ###
