"""add_landing_pages_and_page_views

Revision ID: 24ae512765f6
Revises: f0cbf12d8626
Create Date: 2026-04-26 20:43:33.072265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24ae512765f6'
down_revision: Union[str, Sequence[str], None] = 'f0cbf12d8626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.Text(), nullable=True),
    sa.Column('jsx_code', sa.Text(), nullable=True),
    sa.Column('css_code', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landing_pages_tenant_slug', 'landing_pages', ['tenant_id', 'slug'], unique=True)
    op.create_index('ix_landing_pages_tenant_status', 'landing_pages', ['tenant_id', 'status'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['landing_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_views_created_at', 'page_views', ['created_at'], unique=False)
    op.create_index('ix_page_views_page_id', 'page_views', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_views_page_id', table_name='page_views')
    op.drop_index('ix_page_views_created_at', table_name='page_views')
    op.drop_table('page_views')
    op.drop_index('ix_landing_pages_tenant_status', table_name='landing_pages')
    op.drop_index('ix_landing_pages_tenant_slug', table_name='landing_pages')
    op.drop_table('landing_pages')
    # ### end Alembic commands ###
