"""add courses modules lessons progress products enrollments

Revision ID: 3d5e545f7fec
Revises: 7ad7eae2fd77
Create Date: 2026-04-26 15:28:08.825828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d5e545f7fec'
down_revision: Union[str, Sequence[str], None] = '7ad7eae2fd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('course', 'trail', 'mentorship', 'bundle', name='product_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='product_status'), server_default='draft', nullable=False),
    sa.Column('visibility', sa.Enum('public', 'unlisted', 'private', name='product_visibility'), server_default='public', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gateway_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_days', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_products_tenant_slug')
    )
    op.create_index('ix_products_tenant_status', 'products', ['tenant_id', 'status'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='course_status'), server_default='draft', nullable=False),
    sa.Column('is_free', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('certificate_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_courses_tenant_slug')
    )
    op.create_index('ix_courses_tenant_status', 'courses', ['tenant_id', 'status'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'suspended', 'cancelled', 'refunded', name='enrollment_status'), server_default='active', nullable=False),
    sa.Column('enrolled_by', sa.Enum('webhook', 'manual', 'admin', 'bulk_import', name='enrolled_by'), server_default='manual', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'product_id', name='uq_enrollment_tenant_user_product')
    )
    op.create_index('ix_enrollments_product', 'enrollments', ['product_id'], unique=False)
    op.create_index('ix_enrollments_tenant_user', 'enrollments', ['tenant_id', 'user_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modules_course_order', 'modules', ['course_id', 'order_index'], unique=False)
    op.create_table('product_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'course_id', name='uq_product_courses')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.Enum('video', 'text', 'pdf', 'live', 'quiz', 'embed', 'download', name='lesson_type'), server_default='video', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_free_preview', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_provider', sa.Enum('bunny', 'mux', 'vimeo', 'youtube', 'panda', 'custom', name='video_provider'), nullable=True),
    sa.Column('video_external_id', sa.String(length=255), nullable=True),
    sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('embed_url', sa.String(length=500), nullable=True),
    sa.Column('drip_type', sa.Enum('immediate', 'fixed_date', 'days_after_enrollment', 'prerequisite', name='drip_type'), server_default='immediate', nullable=False),
    sa.Column('drip_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lessons_module_order', 'lessons', ['module_id', 'order_index'], unique=False)
    op.create_index('ix_lessons_tenant', 'lessons', ['tenant_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watch_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_progress_user_lesson')
    )
    op.create_index('ix_lesson_progress_lesson', 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index('ix_lesson_progress_user_lesson', 'lesson_progress', ['user_id', 'lesson_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_user_lesson', 'notes', ['user_id', 'lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_user_lesson', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_lesson_progress_user_lesson', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_lesson', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index('ix_lessons_tenant', table_name='lessons')
    op.drop_index('ix_lessons_module_order', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('product_courses')
    op.drop_index('ix_modules_course_order', table_name='modules')
    op.drop_table('modules')
    op.drop_index('ix_enrollments_tenant_user', table_name='enrollments')
    op.drop_index('ix_enrollments_product', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_courses_tenant_status', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_products_tenant_status', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
