"""add webhook_logs and leads tables

Revision ID: 5de87816aeec
Revises: 3d5e545f7fec
Create Date: 2026-04-26 16:03:38.943647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de87816aeec'
down_revision: Union[str, Sequence[str], None] = '3d5e545f7fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('hotmart_checkout', 'kiwify_checkout', 'greenn_checkout', 'landing_page', name='lead_source'), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_tenant_email', 'leads', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_leads_tenant_source', 'leads', ['tenant_id', 'source'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('hotmart', 'kiwify', 'greenn', 'monetizze', 'stripe', 'custom', name='webhook_provider'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_logs_tenant_processed', 'webhook_logs', ['tenant_id', 'processed'], unique=False)
    op.create_index('ix_webhook_logs_tenant_provider_received', 'webhook_logs', ['tenant_id', 'provider', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_logs_tenant_provider_received', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_tenant_processed', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('ix_leads_tenant_source', table_name='leads')
    op.drop_index('ix_leads_tenant_email', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
